import * as SDK from '../../core/sdk/sdk.js';
import * as UI from '../../ui/legacy/legacy.js';
export declare const setThrottleDisabledForDebugging: (enable: boolean) => void;
export declare class ServiceWorkersView extends UI.Widget.VBox implements SDK.TargetManager.SDKModelObserver<SDK.ServiceWorkerManager.ServiceWorkerManager> {
    currentWorkersView: UI.ReportView.ReportView;
    private readonly toolbar;
    private readonly sections;
    private manager;
    private securityOriginManager;
    private readonly sectionToRegistration;
    private readonly eventListeners;
    constructor();
    private createOthersOriginView;
    private setupToolbar;
    modelAdded(serviceWorkerManager: SDK.ServiceWorkerManager.ServiceWorkerManager): void;
    modelRemoved(serviceWorkerManager: SDK.ServiceWorkerManager.ServiceWorkerManager): void;
    private getTimeStamp;
    private updateSectionVisibility;
    private registrationUpdated;
    private gcRegistrations;
    private getReportViewForOrigin;
    private updateRegistration;
    private registrationDeleted;
    private removeRegistrationFromList;
    private isRegistrationVisible;
    private updateListVisibility;
}
export declare class Section extends UI.Widget.VBox {
    private manager;
    section: UI.ReportView.Section;
    registration: SDK.ServiceWorkerManager.ServiceWorkerRegistration;
    private fingerprint;
    private readonly pushNotificationDataSetting;
    private readonly syncTagNameSetting;
    private readonly periodicSyncTagNameSetting;
    private readonly updateCycleView;
    private readonly clientInfoCache;
    private readonly throttler;
    constructor(manager: SDK.ServiceWorkerManager.ServiceWorkerManager, section: UI.ReportView.Section, registration: SDK.ServiceWorkerManager.ServiceWorkerRegistration);
    private renderHeaderButtons;
    private renderSyncNotificationField;
    scheduleUpdate(): void;
    private renderVersion;
    private renderClientsField;
    private renderSourceField;
    private renderStatusField;
    performUpdate(): Promise<void>;
    private unregisterButtonClicked;
    private renderUpdateCycleField;
    private renderRouterField;
    private updateButtonClicked;
    private networkRequestsClicked;
    private push;
    private sync;
    private periodicSync;
    private renderClientInfo;
    private activateTarget;
    private startButtonClicked;
    private skipButtonClicked;
    private stopButtonClicked;
}
