name: build

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3 \
            git \
            curl \
            gn \
            npm

      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1

      - name: Fetch devtools-frontend
        run: fetch devtools-frontend

      - name: Build devtools-frontend
        run: |
          cd devtools-frontend
          gclient sync
          gn gen out/Default
          autoninja -C out/Default

      - name: Create commit data
        id: create_commit
        run: |
          current_date=$(date +"%d-%m-%Y")
          latest_commit_full=$(git ls-remote https://chromium.googlesource.com/devtools/devtools-frontend.git HEAD | cut -f 1)
          latest_commit_short=${latest_commit_full:0:7}
          commit_title="Build $current_date"
          commit_description="Latest devtools frontend commit: [${latest_commit_short}](https://chromium.googlesource.com/devtools/devtools-frontend.git/+/${latest_commit_full})"
          branch_name="build/${current_date}"
          echo "branch_name=${branch_name}" >> $GITHUB_OUTPUT
          echo "commit_title=${commit_title}" >> $GITHUB_OUTPUT
          echo "commit_description=${commit_description}" >> $GITHUB_OUTPUT

      - name: Open PR
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: ${{ steps.create_commit.outputs.branch_name }}
          title: ${{ steps.create_commit.outputs.commit_title }}
          body: ${{ steps.create_commit.outputs.commit_description }}
          commit-message: ${{ steps.create_commit.outputs.commit_description }}
          labels: auto-build

      # - name: Merge PR
      #   uses: peter-evans/enable-pull-request-automerge@v3
      #   with:
      #     pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
      #     merge-method: squash
