import '../../ui/legacy/legacy.js';
import * as SDK from '../../core/sdk/sdk.js';
import * as UI from '../../ui/legacy/legacy.js';
import { WebAudioModel } from './WebAudioModel.js';
export declare class WebAudioView extends UI.ThrottledWidget.ThrottledWidget implements SDK.TargetManager.SDKModelObserver<WebAudioModel> {
    private readonly contentContainer;
    private readonly detailViewContainer;
    private graphManager;
    private readonly landingPage;
    private readonly summaryBarContainer;
    private readonly contextSelectorPlaceholderText;
    private readonly contextSelectorElement;
    private readonly contextSelectorItems;
    private readonly contextSelectorToolbarItem;
    constructor();
    wasShown(): void;
    willHide(): void;
    modelAdded(webAudioModel: WebAudioModel): void;
    modelRemoved(webAudioModel: WebAudioModel): void;
    doUpdate(): Promise<void>;
    private addEventListeners;
    private removeEventListeners;
    private addContextSelectorPlaceholderOption;
    private onContextSelectorListItemReplaced;
    private selectedContext;
    private onContextSelectorSelectionChanged;
    private titleForContext;
    private contextCreated;
    private contextDestroyed;
    private contextChanged;
    private reset;
    private suspendModel;
    private audioListenerCreated;
    private audioListenerWillBeDestroyed;
    private audioNodeCreated;
    private audioNodeWillBeDestroyed;
    private audioParamCreated;
    private audioParamWillBeDestroyed;
    private nodesConnected;
    private nodesDisconnected;
    private nodeParamConnected;
    private nodeParamDisconnected;
    private updateDetailView;
    private updateSummaryBar;
    private clearSummaryBar;
    private pollRealtimeData;
}
