import * as Platform from '../../core/platform/platform.js';
import type * as CPUProfile from '../../models/cpu_profile/cpu_profile.js';
import * as UI from '../../ui/legacy/legacy.js';
export declare class ProfileEntry {
    searchMatchedSelfColumn: boolean;
    searchMatchedTotalColumn: boolean;
    searchMatchedFunctionColumn: boolean;
    profileNode: CPUProfile.ProfileTreeModel.ProfileNode;
    tree: ProfileDataGridTree;
    childrenByCallUID: Map<string, ProfileEntry>;
    lastComparator: unknown;
    callUID: string;
    self: number;
    total: number;
    functionName: string;
    readonly deoptReason: string;
    url: Platform.DevToolsPath.UrlString;
    populated: boolean;
    savedSelf?: number;
    savedTotal?: number;
    savedChildren?: ProfileEntry[];
    children: ProfileEntry[];
    parent: ProfileEntry | ProfileDataGridTree | null;
    expanded: boolean;
    private hasChildrenInternal;
    private savedPosition;
    constructor(profileNode: CPUProfile.ProfileTreeModel.ProfileNode, owningTree: ProfileDataGridTree, hasChildren: boolean);
    static sort<T>(gridNodeGroups: ProfileEntry[][], comparator: (arg0: T, arg1: T) => number, force: boolean): void;
    static merge(container: ProfileDataGridTree | ProfileEntry, child: ProfileEntry, shouldAbsorb: boolean): void;
    static populate(container: ProfileDataGridTree | ProfileEntry): void;
    hasChildren(): boolean;
    setHasChildren(hasChildren: boolean): void;
    appendChild(child: ProfileEntry): void;
    insertChild(child: ProfileEntry, index: number): void;
    removeChild(child: ProfileEntry): void;
    removeChildren(): void;
    findChild(node: CPUProfile.ProfileTreeModel.ProfileNode): ProfileEntry | null;
    get selfPercent(): number;
    get totalPercent(): number;
    populate(): void;
    populateChildren(): void;
    save(): void;
    restore(): void;
    merge(child: ProfileEntry, shouldAbsorb: boolean): void;
    savePosition(): void;
    restorePosition(): void;
    sort(comparator: (arg0: ProfileEntry, arg1: ProfileEntry) => number, force: boolean): void;
}
export declare class ProfileDataGridTree implements UI.SearchableView.Searchable {
    tree: this;
    self: number;
    children: ProfileEntry[];
    readonly formatter: Formatter;
    readonly searchableView: UI.SearchableView.SearchableView;
    total: number;
    lastComparator: ((arg0: ProfileEntry, arg1: ProfileEntry) => number) | null;
    childrenByCallUID: Map<string, ProfileEntry>;
    deepSearch: boolean;
    populated: boolean;
    searchResults: Array<{
        profileNode: ProfileEntry;
    }>;
    savedTotal?: number;
    savedChildren?: ProfileEntry[] | null;
    searchResultIndex: number;
    constructor(formatter: Formatter, searchableView: UI.SearchableView.SearchableView, total: number);
    static propertyComparator(property: string, isAscending: boolean): (arg0: Record<string, unknown>, arg1: Record<string, unknown>) => number;
    get expanded(): boolean;
    appendChild(child: ProfileEntry): void;
    focus(_profileDataGridNode: ProfileEntry): void;
    exclude(_profileDataGridNode: ProfileEntry): void;
    insertChild(child: ProfileEntry, index: number): void;
    removeChild(child: ProfileEntry): void;
    removeChildren(): void;
    populateChildren(): void;
    findChild(node: CPUProfile.ProfileTreeModel.ProfileNode): ProfileEntry | null;
    sort<T>(comparator: (arg0: T, arg1: T) => number, force: boolean): void;
    save(): void;
    restore(): void;
    matchFunction(searchConfig: UI.SearchableView.SearchConfig): ((arg0: ProfileEntry) => boolean) | null;
    performSearch(searchConfig: UI.SearchableView.SearchConfig, _shouldJump: boolean, jumpBackwards?: boolean): void;
    onSearchCanceled(): void;
    jumpToNextSearchResult(): void;
    jumpToPreviousSearchResult(): void;
    supportsCaseSensitiveSearch(): boolean;
    supportsWholeWordSearch(): boolean;
    supportsRegexSearch(): boolean;
    jumpToSearchResult(index: number): void;
}
export interface Formatter {
    formatValue(value: number, node: ProfileEntry): string;
    formatValueAccessibleText(value: number, node: ProfileEntry): string;
    formatPercent(value: number, node: ProfileEntry): string;
}
